import { Language, NetworkContent } from '@/types';

export const NETWORK_CONTENT: Record<Language, NetworkContent> = {
  en: {
    title: 'BUSINESS NETWORKS',
    items: {
      en: [
        'Present in 11 countries and territories',
        'Digital services serve over 270 million customers worldwide',
        'Coverage across Asia, Africa, and the Americas',
        'Leading provider of telecommunications and digital services',
        'Comprehensive solutions: mobile, internet, digital entertainment, and fintech',
        'Strong commitment to innovation and technology advancement',
        'Strategic partnerships with global technology leaders',
        'Continuous expansion of network infrastructure and service quality',
      ],
      vi: [
        'Hiện diện tại 11 quốc gia và vùng lãnh thổ',
        'Dịch vụ số phục vụ hơn 270 triệu khách hàng trên toàn thế giới',
        'Phủ sóng tại Châu Á, Châu Phi và Châu Mỹ',
        'Nhà cung cấp hàng đầu về viễn thông và dịch vụ số',
        'Giải pháp toàn diện: di động, internet, giải trí số và fintech',
        'Cam kết mạnh mẽ về đổi mới và phát triển công nghệ',
        'Đối tác chiến lược với các tập đoàn công nghệ hàng đầu thế giới',
        'Không ngừng mở rộng hạ tầng mạng và nâng cao chất lượng dịch vụ',
      ],
      zh: [
        '在11个国家和地区开展业务',
        '数字服务为超过2.7亿客户提供服务',
        '覆盖亚洲、非洲和美洲',
        '领先的电信和数字服务提供商',
        '全面解决方案：移动、互联网、数字娱乐和金融科技',
        '致力于创新和技术进步',
        '与全球技术领导者的战略合作伙伴关系',
        '持续扩展网络基础设施和服务质量',
      ],
      fr: [
        'Présent dans 11 pays et territoires',
        'Services numériques desservant plus de 270 millions de clients dans le monde entier',
        'Couverture en Asie, en Afrique et dans les Amériques',
        'Principal fournisseur de services de télécommunications et numériques',
        'Solutions complètes : mobile, internet, divertissement numérique et fintech',
        'Engagement fort envers l\'innovation et l\'avancement technologique',
        'Partenariats stratégiques avec les leaders technologiques mondiaux',
        'Expansion continue de l\'infrastructure réseau et de la qualité des services',
      ],
    },
  },
  vi: {
    title: 'MẠNG LƯỚI KINH DOANH',
    items: {
      en: [
        'Present in 11 countries and territories',
        'Digital services serve over 270 million customers worldwide',
        'Coverage across Asia, Africa, and the Americas',
        'Leading provider of telecommunications and digital services',
        'Comprehensive solutions: mobile, internet, digital entertainment, and fintech',
        'Strong commitment to innovation and technology advancement',
        'Strategic partnerships with global technology leaders',
        'Continuous expansion of network infrastructure and service quality',
      ],
      vi: [
        'Hiện diện tại 11 quốc gia và vùng lãnh thổ',
        'Dịch vụ số phục vụ hơn 270 triệu khách hàng trên toàn thế giới',
        'Phủ sóng tại Châu Á, Châu Phi và Châu Mỹ',
        'Nhà cung cấp hàng đầu về viễn thông và dịch vụ số',
        'Giải pháp toàn diện: di động, internet, giải trí số và fintech',
        'Cam kết mạnh mẽ về đổi mới và phát triển công nghệ',
        'Đối tác chiến lược với các tập đoàn công nghệ hàng đầu thế giới',
        'Không ngừng mở rộng hạ tầng mạng và nâng cao chất lượng dịch vụ',
      ],
      zh: [
        '在11个国家和地区开展业务',
        '数字服务为超过2.7亿客户提供服务',
        '覆盖亚洲、非洲和美洲',
        '领先的电信和数字服务提供商',
        '全面解决方案：移动、互联网、数字娱乐和金融科技',
        '致力于创新和技术进步',
        '与全球技术领导者的战略合作伙伴关系',
        '持续扩展网络基础设施和服务质量',
      ],
      fr: [
        'Présent dans 11 pays et territoires',
        'Services numériques desservant plus de 270 millions de clients dans le monde entier',
        'Couverture en Asie, en Afrique et dans les Amériques',
        'Principal fournisseur de services de télécommunications et numériques',
        'Solutions complètes : mobile, internet, divertissement numérique et fintech',
        'Engagement fort envers l\'innovation et l\'avancement technologique',
        'Partenariats stratégiques avec les leaders technologiques mondiaux',
        'Expansion continue de l\'infrastructure réseau et de la qualité des services',
      ],
    },
  },
  zh: {
    title: '商业网络',
    items: {
      en: [
        'Present in 11 countries and territories',
        'Digital services serve over 270 million customers worldwide',
        'Coverage across Asia, Africa, and the Americas',
        'Leading provider of telecommunications and digital services',
        'Comprehensive solutions: mobile, internet, digital entertainment, and fintech',
        'Strong commitment to innovation and technology advancement',
        'Strategic partnerships with global technology leaders',
        'Continuous expansion of network infrastructure and service quality',
      ],
      vi: [
        'Hiện diện tại 11 quốc gia và vùng lãnh thổ',
        'Dịch vụ số phục vụ hơn 270 triệu khách hàng trên toàn thế giới',
        'Phủ sóng tại Châu Á, Châu Phi và Châu Mỹ',
        'Nhà cung cấp hàng đầu về viễn thông và dịch vụ số',
        'Giải pháp toàn diện: di động, internet, giải trí số và fintech',
        'Cam kết mạnh mẽ về đổi mới và phát triển công nghệ',
        'Đối tác chiến lược với các tập đoàn công nghệ hàng đầu thế giới',
        'Không ngừng mở rộng hạ tầng mạng và nâng cao chất lượng dịch vụ',
      ],
      zh: [
        '在11个国家和地区开展业务',
        '数字服务为超过2.7亿客户提供服务',
        '覆盖亚洲、非洲和美洲',
        '领先的电信和数字服务提供商',
        '全面解决方案：移动、互联网、数字娱乐和金融科技',
        '致力于创新和技术进步',
        '与全球技术领导者的战略合作伙伴关系',
        '持续扩展网络基础设施和服务质量',
      ],
      fr: [
        'Présent dans 11 pays et territoires',
        'Services numériques desservant plus de 270 millions de clients dans le monde entier',
        'Couverture en Asie, en Afrique et dans les Amériques',
        'Principal fournisseur de services de télécommunications et numériques',
        'Solutions complètes : mobile, internet, divertissement numérique et fintech',
        'Engagement fort envers l\'innovation et l\'avancement technologique',
        'Partenariats stratégiques avec les leaders technologiques mondiaux',
        'Expansion continue de l\'infrastructure réseau et de la qualité des services',
      ],
    },
  },
  fr: {
    title: "RÉSEAUX D'AFFAIRES",
    items: {
      en: [
        'Present in 11 countries and territories',
        'Digital services serve over 270 million customers worldwide',
        'Coverage across Asia, Africa, and the Americas',
        'Leading provider of telecommunications and digital services',
        'Comprehensive solutions: mobile, internet, digital entertainment, and fintech',
        'Strong commitment to innovation and technology advancement',
        'Strategic partnerships with global technology leaders',
        'Continuous expansion of network infrastructure and service quality',
      ],
      vi: [
        'Hiện diện tại 11 quốc gia và vùng lãnh thổ',
        'Dịch vụ số phục vụ hơn 270 triệu khách hàng trên toàn thế giới',
        'Phủ sóng tại Châu Á, Châu Phi và Châu Mỹ',
        'Nhà cung cấp hàng đầu về viễn thông và dịch vụ số',
        'Giải pháp toàn diện: di động, internet, giải trí số và fintech',
        'Cam kết mạnh mẽ về đổi mới và phát triển công nghệ',
        'Đối tác chiến lược với các tập đoàn công nghệ hàng đầu thế giới',
        'Không ngừng mở rộng hạ tầng mạng và nâng cao chất lượng dịch vụ',
      ],
      zh: [
        '在11个国家和地区开展业务',
        '数字服务为超过2.7亿客户提供服务',
        '覆盖亚洲、非洲和美洲',
        '领先的电信和数字服务提供商',
        '全面解决方案：移动、互联网、数字娱乐和金融科技',
        '致力于创新和技术进步',
        '与全球技术领导者的战略合作伙伴关系',
        '持续扩展网络基础设施和服务质量',
      ],
      fr: [
        'Présent dans 11 pays et territoires',
        'Services numériques desservant plus de 270 millions de clients dans le monde entier',
        'Couverture en Asie, en Afrique et dans les Amériques',
        'Principal fournisseur de services de télécommunications et numériques',
        'Solutions complètes : mobile, internet, divertissement numérique et fintech',
        'Engagement fort envers l\'innovation et l\'avancement technologique',
        'Partenariats stratégiques avec les leaders technologiques mondiaux',
        'Expansion continue de l\'infrastructure réseau et de la qualité des services',
      ],
    },
  },
};
